// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4NzkRgf6ohaAkLknOts5rhz3JKIiHNT8',
    appId: '1:503914753532:web:9de1153be7a0255cc3d679',
    messagingSenderId: '503914753532',
    projectId: 'guest-ee1b0',
    authDomain: 'guest-ee1b0.firebaseapp.com',
    storageBucket: 'guest-ee1b0.appspot.com',
    measurementId: 'G-V0X3WWTJJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT1SCUODt6GU5T9wUc1zU2ix2jX3JI-tM',
    appId: '1:503914753532:android:4fdb0645fe95dc82c3d679',
    messagingSenderId: '503914753532',
    projectId: 'guest-ee1b0',
    storageBucket: 'guest-ee1b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0BTeNyl2S_trz5rDfsVfDU-nKRt3Zxg',
    appId: '1:503914753532:ios:c897003960ce1ee4c3d679',
    messagingSenderId: '503914753532',
    projectId: 'guest-ee1b0',
    storageBucket: 'guest-ee1b0.appspot.com',
    iosBundleId: 'com.example.guest',
  );
}
